"""empty message

Revision ID: 4c0eb3db21e7
Revises: aa907d41585b
Create Date: 2019-06-09 16:58:13.320905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0eb3db21e7'
down_revision = 'aa907d41585b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('first_last_uni_emp', 'employee', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('first_last_uni_emp', 'employee', ['first_name', 'last_name'])
    # ### end Alembic commands ###
