"""empty message

Revision ID: 620cfca70dce
Revises: 
Create Date: 2019-06-07 15:29:38.202302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620cfca70dce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('first_last_uni_emp', 'employee', ['first_name', 'last_name'])
    op.drop_constraint('unique_employee_name', 'employee', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_employee_name', 'employee', ['first_name', 'last_name'])
    op.drop_constraint('first_last_uni_emp', 'employee', type_='unique')
    # ### end Alembic commands ###
