"""empty message

Revision ID: aa907d41585b
Revises: 
Create Date: 2019-06-09 16:57:45.375306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa907d41585b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('first_last_uni_emp', 'employee', ['first_name', 'last_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('first_last_uni_emp', 'employee', type_='unique')
    # ### end Alembic commands ###
