"""empty message

Revision ID: b0e895f42638
Revises: 
Create Date: 2019-06-06 13:28:55.645540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e895f42638'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'last_name', name='unique_employee_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shift_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_tip_pool', sa.Float(), nullable=True),
    sa.Column('cash_tip_wage', sa.Float(), nullable=True),
    sa.Column('cred_tip_pool', sa.Float(), nullable=True),
    sa.Column('cred_tip_wage', sa.Float(), nullable=True),
    sa.Column('shift_hours', sa.Float(), nullable=True),
    sa.Column('tip_hours', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('cash_tip_pool < 10000', name='check_cash_tip_pool_max'),
    sa.CheckConstraint('cash_tip_pool > 0', name='check_cash_tip_pool_min'),
    sa.CheckConstraint('cash_tip_wage < 100', name='check_cash_tip_wage_max'),
    sa.CheckConstraint('cash_tip_wage > 0', name='check_cash_tip_wage_min'),
    sa.CheckConstraint('cred_tip_pool < 10000', name='check_cc_tip_pool_max'),
    sa.CheckConstraint('cred_tip_pool > 0', name='check_cc_tip_pool_min'),
    sa.CheckConstraint('cred_tip_wage < 100', name='check_cc_tip_wage_max'),
    sa.CheckConstraint('cred_tip_wage > 0', name='check_cc_tip_wage_min'),
    sa.CheckConstraint('shift_hours < 90', name='check_total_shift_hours_max'),
    sa.CheckConstraint('shift_hours > 0', name='check_total_shift_hours_min'),
    sa.CheckConstraint('tip_hours < 90', name='check_total_tip_hours_max'),
    sa.CheckConstraint('tip_hours > 0', name='check_total_tip_hours_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_reports_start_date'), 'shift_reports', ['start_date'], unique=True)
    op.create_table('employee_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_tips', sa.Float(), nullable=True),
    sa.Column('cred_tips', sa.Float(), nullable=True),
    sa.Column('tip_role', sa.Enum('SERVICE', 'SUPPORT', name='tip_role'), nullable=True),
    sa.Column('shift_hours', sa.Float(), nullable=True),
    sa.Column('tip_hours', sa.Float(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('cash_tips < 10000', name='check_cash_tips_max'),
    sa.CheckConstraint('cash_tips > 0', name='check_cash_tips_min'),
    sa.CheckConstraint('cred_tips < 10000', name='check_cc_tips_max'),
    sa.CheckConstraint('cred_tips > 0', name='check_cc_tips_min'),
    sa.CheckConstraint('shift_hours < 24.0', name='check_shift_hours_max'),
    sa.CheckConstraint('shift_hours > 0', name='check_shift_hours_min'),
    sa.CheckConstraint('tip_hours < 24.0', name='check_tip_hours_max'),
    sa.CheckConstraint('tip_hours > 0', name='check_tip_hours_min'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('users')
    op.drop_table('employee_reports')
    op.drop_index(op.f('ix_shift_reports_start_date'), table_name='shift_reports')
    op.drop_table('shift_reports')
    op.drop_table('roles')
    op.drop_table('employees')
    # ### end Alembic commands ###
